### ISSUE TITLE
Possibility to render radios as checkboxes (and vice versa?)

### ISSUE THREAD

**Issue by Misiur** [flatlogic/awesome-bootstrap-checkbox#10]
Hi, I love this script. I'd love to see possilbility of rendering radios as checkboxes. I understand if you don't want to implement it (as it's 50% css filesize more), but still - it would be awesome.

Thanks

**Comment by cjroth** [comment]
+1

**Comment by cjroth** [comment]
Sent pull request.

**Comment by EralpB** [comment]
Can you please merge this in?

**Comment by okendoken** [comment]
@Misiur @EralpB merged

@cjroth special thanks ;)

**Comment by cjroth** [comment]
:+1: :)
