### ISSUE TITLE
Huge size of font files makes it inefficient to use this useful tool

### ISSUE THREAD

**Issue by badihi** [flatlogic/awesome-bootstrap-checkbox#104]
Hello friends,
I have to thank you for your useful and beautiful project, but there is something that stops me from using this.
You are embedding some huge font files, only for a tick sign! It seems to be more efficient to use images instead of these fonts. This may make problems for people that do not want to use other symbols provided by the font.
I hope that you care about my issue.
Thanks

**Comment by pmfx** [comment]
You can customize your FontAwesome icon set with a generator like https://icomoon.io/ (it is really good) so as a result you will only use icons your project needs.

**Comment by raxraj** [comment]
And the way Font-awesome is integrated it won't work if the user doesn't adds Fontawesome, Plus it is not in the documentation !! I'm working on a Solution.
