### ISSUE TITLE
Bootstrap v4.0.0-alpha.6: No mixin named tab-focus

### ISSUE THREAD

**Issue by sgillespie** [flatlogic/awesome-bootstrap-checkbox#111]
Bootstrap has just ripped out the `tab-focus` mixin:

https://github.com/twbs/bootstrap/commit/22fcac2ceac9edf1f7fdffd27215e17833b6d68b

So this no longer compiles with webpack, using awesome-bootstrap-checkbox.scss:

```
&:focus + label::before{
      @include tab-focus();
}
```

https://github.com/flatlogic/awesome-bootstrap-checkbox/blob/d0bfdad0365f0d765b1a81d7fafdd894565bce7d/awesome-bootstrap-checkbox.scss#L83
https://github.com/flatlogic/awesome-bootstrap-checkbox/blob/d0bfdad0365f0d765b1a81d7fafdd894565bce7d/awesome-bootstrap-checkbox.scss#L208

**Comment by karolyi** [comment]
+1, subscribing for the fix

**Comment by dimvic** [comment]
+1, also after declaring tab-focus the icons are not positioned very well, any hope for an update?

**Comment by karolyi** [comment]
@dimvic my temporary fix, put this in a file, and include it in your SASS file.

```sass
// Left out of newest bootstrap, remove in the future when
// https://github.com/flatlogic/awesome-bootstrap-checkbox/issues/111
// gets fixed.

// WebKit-style focus
@mixin tab-focus {
  // WebKit-specific. Other browsers will keep their default outline style.
  // (Initially tried to also force default via `outline: initial`,
  // but that seems to erroneously remove the outline in Firefox altogether.)
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}

// awesome-bootstrap-checkbox adjustment to not break when the viewport
// is narrow
.abc-checkbox {
  label {
    display: inline;

    &::after,
    &::before {
      @if $enable-rounded {
        // Manually use the if/else instead of the mixin to account for iOS override
        border-radius: $input-border-radius;
      }

      top: 9px;
    }

    &:before {
      @include box-shadow($input-box-shadow);
    }
  }
}

.has-danger {
  .abc-checkbox {
    label {
      &:before {
        border-color: $brand-danger;
      }
    }
  }
}
```

**Comment by dimvic** [comment]
thank you very much for sharing this, it would be nice for the project if you submitted a PR for this as well

**Comment by karolyi** [comment]
I'm not sure we have to do this. the `tab-focus` was removed for a reason, so I'd better give a chance to the checkbox dev guy to figure out if the project still needs that mixin, which is probably a no.

for the other stuff, that would be nice to have, as the `has-danger` class and the positioning is a huge fix to the original CSS.

@flatlogic

**Comment by DimaSavchenko** [comment]
#98 same issue

**Comment by DimaSavchenko** [comment]
I have updated to v4.0.0-alpha.6. But appear strange selection. 

![image](https://cloud.githubusercontent.com/assets/11638499/23304228/af1dffb0-faa9-11e6-86b5-60e6906c78e7.png)

Maybe anyone have thoughts?

**Comment by karolyi** [comment]
what is strange on this?

**Comment by karolyi** [comment]
btw I introduced the `display: inline` and the pixel adjustments because of the breaking lines.

also, I added the `has-danger` class handling, if you update the project, it would be beneficial to add those too.

see my comment with the SASS adjustment above.

**Comment by karolyi** [comment]
@DimaSavchenko thx & cheers :)
