### ISSUE TITLE
CSS RTL Support (Checkbox and Radio)

### ISSUE THREAD

**Issue by JTCE** [flatlogic/awesome-bootstrap-checkbox#115]
I can do a PR sometime in the next couple weeks if you want this.
Tested via [bootsnipp](http://bootsnipp.com/) "[Bootstrap Checkboxes/Radios](http://bootsnipp.com/snippets/ZkMKE)"
Add the following code before or after one of the checkbox divs:
```
<div class="checkbox rtl checkbox-danger">
    <input id="checkbox0" type="checkbox">
    <label for="checkbox0">
        Default RTL
    </label>
</div>
```

CSS Additions
```
.checkbox.rtl {
  padding-left: 0px; 
  padding-right: 20px; }
  .checkbox.rtl label {
    padding-left: 0px;
    padding-right: 5px; }
    .checkbox.rtl label::before {
      left: auto;
      right: 2px;
      margin-left: 0;
      margin-right: -20px; }
    .checkbox.rtl label::after {
      left: auto;
      right: 0;
      margin-left: 0px;
      margin-right: -20px;
      padding-left: 0px;
      padding-right: 3px; }
  .checkbox.rtl input[type="checkbox"]{
    margin-left: 0px;
  }

.radio.rtl {
  padding-left: 0px; 
  padding-right: 20px; }
  .radio.rtl label {
    padding-left: 0px;
    padding-right: 5px; }
    .radio.rtl label::before {
      left: auto;
      right: -3px;
      margin-left: 0;
      margin-right: -20px; }
    .radio.rtl label::after {
      left: auto;
      right: 0;
      margin-left: 0px;
      margin-right: -20px;
      padding-left: 0px;
      padding-right: 3px; }
  .radio.rtl input[type="radio"]{
    margin-left: 0px;
  }
```

**Comment by DimaSavchenko** [comment]
Hi, create RP, please. Maybe  issue #35  will be helpful for you.
Thanks!

**Comment by moharrum** [comment]
Thank you @JTCE ,

This just saved my day, why this is not added yet!!

**Comment by JTCE** [comment]
@moharrum glad it helped you out! Pleased I could give back to the community, after all, this is a great component! Just wish my PR was accepted.

**Comment by KillerSquid** [comment]
I've been fighting with this for over two hours now.  Your code fixed it in 5 seconds.  THANK YOU SO MUCH!!

**Comment by JTCE** [comment]
@KillerSquid glad it served you well! Gives me joy knowing it's useful! A small contribution for all the dedicated hours the authors put in this nice add-on.

**Comment by ivonsue** [comment]
Thank you! saved my day <3

**Comment by c3oussama** [comment]
thx you man :)
