### ISSUE TITLE
Standalone usage without bootstrap?

### ISSUE THREAD

**Issue by baszero** [flatlogic/awesome-bootstrap-checkbox#117]
Hi, i want to use awesome-bootstrap-checkbox without bootstrap.
What is the easiest way to load the font from my own servers? Which files do I need and how to reference them?

**Comment by DimaSavchenko** [comment]
Hi, @baszero! You can use just awesome-bootstrap-checkbox.css or change awesome-bootstrap-checkbox.scss

**Comment by baszero** [comment]
Thanks, but I tried that in the first place but it didn't work, the checkbox contained an illegal character (font that I don't have). 

I continued by importing also `font-awesome.css` from this project, the check mark appeared by then but it didn't look good (too small in the checkbox). 
So I stopped working on this as I don't have much time to spend on beautifying checkboxes...

Is there a working example somewhere that just uses `awesome-bootstrap-checkbox.css` only? The demo is also loading `font-awesome.css` and `build.css`

**Comment by wartab** [comment]
You need to have the fonts folder of font-awesome accessible aswell.

**Comment by baszero** [comment]
As I wrote, I made the font-awesome available but it just didn't look correct.
I need a working sample that runs without bootstrap.

**Comment by wartab** [comment]
Indeed, I noticed a slight difference between a Boostrap-less rendering and one with Bootstrap. Those difference are mainly due to line-height: 1.42857143 not being applied to body.

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <style>
        body {
            line-height: 1.42857143;
        }
    </style>
    
    <link rel="stylesheet" href="../node_modules/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="../node_modules/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css">
</head>
<body>
    <div class="checkbox checkbox-inline checkbox-info">
        <input type="checkbox" id="test" name="test">
        <label for="test">Test</label>
    </div>

</body>
</html>
```

There is a slight horizontal shift to the left of the checkmark, but I sadly do not have the time to figure out what causes that in Bootstrap.
