### ISSUE TITLE
printing - selected radio button not visible

### ISSUE THREAD

**Issue by LeiChat** [flatlogic/awesome-bootstrap-checkbox#125]
When printing (in IE11) the radio buttons do not display the checked status.
The text labels and circle outlines are displayed.

Does not appear to be an issue with the checkbox classes.
When using the "As Checkboxes" implementation the tick is displayed.

Here's a screenshot of the IE11 Print Preview of the demo page...

![radio-print-issue](https://user-images.githubusercontent.com/23559551/27094021-a926d49e-5060-11e7-9c67-8bbcac697e5f.PNG)

**Comment by PawOrmstrupMadsen** [comment]
Did you ever manage to solve this ?
