### ISSUE TITLE
Undefined variable: "$input-border-color" in awesome-bootstrap-checkbox.scss

### ISSUE THREAD

**Issue by wdzikowicz** [flatlogic/awesome-bootstrap-checkbox#126]
jspm_packages\npm\awesome-bootstrap-checkbox@1.0.0-alpha.5\awesome-bootstrap-checkbox.scss
Error: Undefined variable: "$input-border-color".

**Comment by winterlimelight** [comment]
If you're in the same position as me, you got this error because you're using bootstrap 3. Change your awesome-bootstrap-checkbox npm version to 0.3.7 (i.e. change package.json then `npm update`) to get bootstrap 3 compatible version.

**Comment by armpogart** [comment]
Same issue here: https://github.com/flatlogic/awesome-bootstrap-checkbox/issues/131

But is there any mention somewhere, that the new versions are bootstrap 4 only and are incompatible with bootstrap 3?
