### ISSUE TITLE
border is not pretty when focus expecially the radio box

### ISSUE THREAD

**Issue by bi-kai** [flatlogic/awesome-bootstrap-checkbox#128]
border is not pretty when focus expecially the radio box:
![image](https://user-images.githubusercontent.com/15070379/29265750-c5ad17d8-8114-11e7-93d9-dcc9294f2421.png)
will you hide it?

**Comment by creativetags** [comment]
see #134 for a solution

**Comment by bi-kai** [comment]
It seems like the style is still there in the [demo](http://flatlogic.github.io/awesome-bootstrap-checkbox/demo/):
![image](https://user-images.githubusercontent.com/15070379/40471508-80872fca-5f69-11e8-8155-824df49a2a0e.png)
