### ISSUE TITLE
Incompatibility list with bootstrap v4.0.0-beta

### ISSUE THREAD

**Issue by karolyi** [flatlogic/awesome-bootstrap-checkbox#129]
hey,

I'm using `1.0.0-alpha.5`, here's a list of variables that are removed in bootstrap `v4.0.0-beta`:

- `$input-bg-disabled`: renamed to `$input-disabled-bg`
- all the `$brand-xxx` variables are to be reached now via `theme-color("xxx")` (i.e. `$brand-primary` -> `theme-color("primary")`

(I'll extend this list, should I find anything later)

**Comment by KristofMorva** [comment]
Hey, please see #127
