### ISSUE TITLE
Undefined variable: "$form-check-input-gutter"

### ISSUE THREAD

**Issue by armpogart** [flatlogic/awesome-bootstrap-checkbox#131]
When using Sass with `bootstrap-sass` port, I get following error
````
Error: Undefined variable: "$form-check-input-gutter".
        on line 57 of node_modules/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.scss
>>       margin-left: -$form-check-input-gutter;
````

P.S. Using with bootstrap 3.x

**Comment by armpogart** [comment]
There are also other undefined variables, after I define this one. As far as I can see these are all bootstrap 4 variables, but I don't see any mention in Readme or documentation that master branch doesn't support bootstrap 3 anymore.

**Comment by armpogart** [comment]
Installed with npm (https://www.npmjs.com/package/awesome-bootstrap-checkbox)

**Comment by littlefinger42** [comment]
How can i install the correct version for Bootstrap 3 with npm?

**Comment by armpogart** [comment]
The latest alpha is working with bootstrap 3, install it with `npm install awesome-bootstrap-checkbox@1.0.0-alpha.5`
