### ISSUE TITLE
Not working with Asp webforms

### ISSUE THREAD

**Issue by brettwinters** [flatlogic/awesome-bootstrap-checkbox#132]
hello

I can't seem to get it working with Asp.net webforms and BS4-beta. My Code

```
<div class="form-group row">
      <label for="ckbBusinessInheritRoles" class="col-sm-2 col-form-label">Check Me</label>
      <div class="col-1">
              <div class="form-check abc-checkbox">
                   <asp:CheckBox ID="ckbOne" runat="server" CssClass="form-check-input" />
                   <label class="form-check-label" for="ckbBusinessInheritRoles">
             </div>
      </div>
</div>
```

The box renders ok, but it's not checkable. The asp web server inserts a <span> tag around the checkbox which probably prevent the toggle from working. Any solution to this? 

Regards

Brett

**Comment by brettwinters** [comment]
<div class="form-group row">
      <label for="ckbBusinessInheritRoles" class="col-sm-2 col-form-label">Check Me</label>
      <div class="col-1">
              <div class="form-check abc-checkbox">
                   <asp:CheckBox ID="ckbOne" runat="server" CssClass="form-check-input" />
                   <label class="form-check-label" for="ckbBusinessInheritRoles">
             </div>
      </div>
</div>

**Comment by cesarzapatawfm** [comment]
I would try adding the style on page ready via javascript.

**Comment by Katydude** [comment]
I know this issue is old but I encountered it today, more or less. The problem is likely a hidden input or label that's being generated with the same name attribute.
