### ISSUE TITLE
Checkbox Inside table column

### ISSUE THREAD

**Issue by m3ldro** [flatlogic/awesome-bootstrap-checkbox#145]
Hello,
i like this trick very much!
Thanks a lot!

Just one problem... 
it seems to be impossibile to align the checkbox/radio inside a table column (text-align: center).

(please have a look to the screenshot)

There is a way to fix it or i miss something?

Thanks a lot.
![screenshot_38](https://user-images.githubusercontent.com/20204970/52474655-5f472700-2b99-11e9-9177-9d7ae54e472a.png)

**Comment by terryaney** [comment]
I have similar problem.  I get different alignments in thead/tr/th vs tbody/tr/td.  I don't have any alignment specified against them, but cannot for the of me figure out where the alignment issue is.  Below is screen shot of the alignment and the markup.  Any guess on where to look to make the tbody/tr/td line up with the th one?

![image](https://user-images.githubusercontent.com/6237247/58147945-5d721280-7c22-11e9-9797-8f7faee2bf86.png)

**Comment by michaeldaineka** [comment]
Hi! We've resolved your issue by adding 
```
table .checkbox {
  padding-left: 26px;
}
```
