### ISSUE TITLE
Latest version missing from npm?

### ISSUE THREAD

**Issue by karolyi** [flatlogic/awesome-bootstrap-checkbox#149]
Hey,

I see version 2.0.0 is available on here but not on npm. I'm currently in the process of upgrading to bootstrap 5.x, can you please release 2.0.0 on npm?

That would be appreciated.

**Comment by buster1407** [comment]
Having the same issue.

**Comment by SteveW94** [comment]
As this is currently really affecting us, it would be nice if someone could publish the 2.0 release.

If this package is not maintained anymore, maybe fork it and then publish it?

**Comment by Blari** [comment]
We have just updated the package on npm.

**Comment by cecilian** [comment]
Hi, I found there's something strange with v2.0 on npm.

If I download the tar of v2.0 from github, the file `awesome-bootstrap-checkbox.scss` has this:
```
    &::before{
      cursor: pointer;
      content: "";
      display: inline-block;
      position: absolute;
      width: 17px;
      height: 17px;
      top: 2px;
      left: 0;
      margin-left: -$form-check-input-gutter;
      border: $abc-border-width solid $input-border-color;
      border-radius: 3px;
      background-color: #fff;
      @include transition(border 0.15s ease-in-out, color 0.15s ease-in-out);
    }
```
which is correct and works with bootstrap v5

However the version downloaded from npm (as it can be seen also [here](https://www.npmjs.com/package/awesome-bootstrap-checkbox/v/2.0.0?activeTab=code) ) has
```
&::before{
  content: "";
  display: inline-block;
  position: absolute;
  width: 17px;
  height: 17px;
  left: 0;
  margin-left: -20px;
  border: $abc-border-width solid $input-border;
  border-radius: 3px;
  background-color: $input-bg;
  @include transition(border 0.15s ease-in-out, color 0.15s ease-in-out);
}
```
Apart from the line numbers being different, the line `border: $abc-border-width solid $input-border;` breaks with bootstrap v5.

Could there be an issue with the version on npm?
I never encountered this issue before so I apologise in advance if I'm doing something wrong.

**Comment by Blari** [comment]
Hi @cecilian 

Thank you for bringing this to our attention. 

The issue was caused by the npm package being published from the master branch, which did not yet contain the necessary updates for Bootstrap v5 compatibility. We have now published the correct version from the appropriate branch, and the problem should be resolved.

Please update the package from npm, and everything should work as expected. Apologies for any inconvenience this may have caused.

**Comment by cecilian** [comment]
Thank you, it works!
