### ISSUE TITLE
Checkbox with label on the left

### ISSUE THREAD

**Issue by Tchikiiii** [flatlogic/awesome-bootstrap-checkbox#18]
Impossible to have a label on the left and the checkbox on the right?
What could I do to change that?

**Comment by pboutin** [comment]
It's all about CSS restrictions. The checkbox is hidden and then, the label is styled to simulate the checbox. For exemple, to display a "checked" instance, you have :

    .checkbox input[type=checkbox]:checked + label:after { ...

The inverse is not possible (select the label that comes *before* a checked input
