### ISSUE TITLE
Use @input-color for checkbox

### ISSUE THREAD

**Issue by davidxd33** [flatlogic/awesome-bootstrap-checkbox#19]
It makes much more sense just to use @input-color to color the checkboxes. Currently, it uses @gray which does map out to @input-color but when I am customizing my bootstrap variables, I don't want to change my @lighter-gray, I change the @input-color for my inputs.

**Comment by micrum** [comment]
Thx @davidxd33 !
Fixed in [version 0.3.2](https://github.com/flatlogic/awesome-bootstrap-checkbox/releases/tag/v0.3.2)
