### ISSUE TITLE
Tab + Enter

### ISSUE THREAD

**Issue by apex06** [flatlogic/awesome-bootstrap-checkbox#25]
If you tab through checkboxes and hit enter the checkbox won't be selected.

**Comment by okendoken** [comment]
@apex06 as far as I know you have to hit "space", not "enter" in order to check/uncheck checkbox.
It's all working good with space button

**Comment by apex06** [comment]
You are right my fault :) sorry

**Comment by okendoken** [comment]
no problem :)
closing
