### ISSUE TITLE
Component outline

### ISSUE THREAD

**Issue by yuriricci** [flatlogic/awesome-bootstrap-checkbox#32]

**Comment by yuriricci** [comment]
Is there a way to remove the gray outline from the components once selected? Standard ways to do that, like setting css outline style to input elements, does not seem to work.

EDIT
I saw now the problem was already faced, but the style:
.checkbox input[type="checkbox"]:focus + label::before {
  outline: none;
}
does not work for me..

**Comment by matrunchyk** [comment]
Yes, it affects me too. How to remove the outline?

**Comment by yuriricci** [comment]
As seen in another ansower, try this:

.checkbox input[type="checkbox"]:focus + label::before {
   outline: 0px !important;
  -webkit-appearance:none !important;

  -webkit-box-shadow: none !important;
  -moz-box-shadow: none !important;
  box-shadow: none !important;
}

**Comment by matrunchyk** [comment]
Would you please commit this fix?

**Comment by felixcheruiyot** [comment]
Is this done?

**Comment by chitrank-samaiya** [comment]
+1 it helped

**Comment by thatguyyoulove** [comment]
This is great. I would love to see it added to the source.

I can make a pull request, but it looks like the outline was added purposefully.

Any reason specific for this?
Not wanting to be too opinionated with style?

**Comment by okendoken** [comment]
Guys, I do believe that outline has to present on the checkbox. If we remove the outline, it will be impossible to navigate checkboxes with `Tab` & `Space` keys.

**Comment by thatguyyoulove** [comment]
I just tested using `Tab` and `Space` on Chrome with the outline turned off and it worked as per normal. It does, however, feel a little weird as you can't tell which one you are currently on (perhaps that's what you meant by impossible to navigate).

Personally, most of the weirdness comes from the outline being square shaped on rounded checkboxes/radios as well as the default blue color looking strange against the various color options.

Perhaps replacing the actual outline with a box-shadow (which properly conforms to the control's shape) would alleviate the issue enough while retaining accessibility.

Example: 
````
.checkbox input[type="checkbox"]:focus + label::before {
    outline: 0px !important;
    -webkit-appearance:none !important;
    box-shadow: 0px 0px 1px 1px #999 !important;
}
````

**Comment by sestolk** [comment]
@thatguyyoulove That is a perfect solution in my case. Thank you!

**Comment by thatguyyoulove** [comment]
@sestolk 

Good to hear. Just be aware that the shadow will not show on IE8, which is still a supported browser for Bootstrap 3. If that is important, then you might write a IE8 specific fallback to using the outline or the MS proprietary "shadow" filter.
