### ISSUE TITLE
indeterminate checkbox state

### ISSUE THREAD

**Issue by ogazioglu** [flatlogic/awesome-bootstrap-checkbox#33]
Current styles doesn't support the indeterminate states. I know that css can't handle the indeterminate property, but you can support indeterminate states with additional css classes. For ex. when checkbox is indeterminate I can add the **checkbox-indeterminate** class to wrapper. Just need style this class.

**Comment by enumag** [comment]
Is the class actually needed? The `:indeterminate` pseudoclass should be enough imho.

**Comment by ogazioglu** [comment]
probably, but what about browser support?

**Comment by enumag** [comment]
Should be fine unless you care about IE8. https://developer.mozilla.org/en-US/docs/Web/CSS/%3Aindeterminate#Browser_compatibility

**Comment by DimaSavchenko** [comment]
Thanks! Version 0.3.7 is supported the Indeterminate state.
