### ISSUE TITLE
Integration into simple_form

### ISSUE THREAD

**Issue by kockok** [flatlogic/awesome-bootstrap-checkbox#4]
I have spent days to try integrating your css into the simple_form gem, however, with no success.
I tried adding a class into the input column, but it seems not working.

```
f.input :options, as: :boolean, inline_label: 'Option 1', label: false, :class => "checkbox  checkbox-primary"
```

Please advise.

**Comment by kwent** [comment]
Just add `boolean_style: :inline` with simple_form. `input` will not be wrapped in a `label` element and this will work.

**Comment by kockok** [comment]
Sorry for the late response, the solution rocks!

**Comment by gucki** [comment]
@kwent :+1:
