### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by cjroth** [flatlogic/awesome-bootstrap-checkbox#41]
It's unclear to me what the preferred way to build this is. I used sass/less via command line to build it with the build scripts in the demo directory but I was wondering if that is the "right" way you intended to do it. It'd be nice if the sass or less file was the master copy and built into the other two formats using a tool like gulp or grunt.

**Comment by DimaSavchenko** [comment]
Hi, it's very cool. You may do pull reguests. We will be happy. : -)
