### ISSUE TITLE
npm package request

### ISSUE THREAD

**Issue by FSElias** [flatlogic/awesome-bootstrap-checkbox#44]
Hello,
please can you add this project package to npm as you did in bower?
Thank you.

**Comment by jcc2303** [comment]
+1

**Comment by riggerthegeek** [comment]
+1

**Comment by okendoken** [comment]
@FSElias @jcc2303 @riggerthegeek 
Guys, will be ready in a few hours. Thanks for request ;)

**Comment by FSElias** [comment]
:D

**Comment by okendoken** [comment]
Ready.

    npm install awesome-bootstrap-checkbox


Thanks again!
