### ISSUE TITLE
Jquery Check AND Uncheck Checkbox

### ISSUE THREAD

**Issue by lablabo** [flatlogic/awesome-bootstrap-checkbox#46]
Hi Guys
First, Thank You
Have a problem 
how check and uncheck with jquery ?
with jquery, when  uncheck checkboxs , yet checkboxs are selected

MyCode 
------------
			if($(this).is(':checked')){
				$("#pages-result input[type='checkbox']").each(function(){
					$(this).attr("checked","checked");
				});
			}else{
				$("#pages-result input[type='checkbox']").each(function(){
					$(this).removeAttr("checked");
				});
			}

**Comment by PimHaarsma** [comment]
Hi! This will work:
`$(this).prop('checked', true);`
`$(this).prop('checked', false);`

**Comment by lablabo** [comment]
@PimHaarsma Thank You So Much
