### ISSUE TITLE
Frameworks That Generate a Hidden Input Break

### ISSUE THREAD

**Issue by JDurman** [flatlogic/awesome-bootstrap-checkbox#47]
Example:

```
<div class="checkbox" >
                        <input class="inline-block" data-val="true" data-val-required="'Restricted Use Product' must not be empty." id="RestrictedUseProduct" name="RestrictedUseProduct" type="checkbox" value="true">
                        <input name="RestrictedUseProduct" type="hidden" value="false">
                        <label for="RestrictedUseProduct">Restricted Use Product</label>
</div>
```

The example shows the html generated from html helpers in .net MVC or Ruby on Rails. I fixed my problem by using the ~ selector in the file instead of the + selector. Not sure if this is the best solution in the long run though.

**Comment by bogacg** [comment]
I'm having same problem; 
I've chosen to solve it by adding this script: (you can ommit hidden input)
```javascript
        $("#checkboxID").change(function () {
            if (this.checked) {
                this.value = true;
            } else {
                this.value = false;
            }
        });
```

**Comment by DimaSavchenko** [comment]
Guys, thanks! This problem has been solved here:
https://github.com/flatlogic/awesome-bootstrap-checkbox/issues/1
https://github.com/flatlogic/awesome-bootstrap-checkbox/issues/4
