### ISSUE TITLE
awesome-bootstrap-checkbox breaks with Pipeline

### ISSUE THREAD

**Issue by karolyi** [flatlogic/awesome-bootstrap-checkbox#48]
Hey,

since your `demo/bootstrap.css` references [nonexistent font files](https://github.com/flatlogic/awesome-bootstrap-checkbox/blob/master/demo/bootstrap.css#L270), [django-pipeline](https://github.com/cyberdelia/django-pipeline/issues/302) breaks.

Please fix it.

**Comment by DimaSavchenko** [comment]
You don't need referenced from 'demo/bootstrap.css'. Use 'awesome-bootstrap-checkbox.scc/less/scss'.

**Comment by DimaSavchenko** [comment]
You don't need referenced from `demo/bootstrap.css`. Use `awesome-bootstrap-checkbox.scc/less/scss`.

**Comment by karolyi** [comment]
It's not that I need to, nor do I want to. django-pipeline simply copies every files into its static folder, while checking out if every asset is available. The ones you refer in the files I mentioned aren't there, thus the `collectstatic` command fails.

However, the error didn't occur recently, although I didn't test it thoroughly but might be that the pipeline guys fixed the issue, after all the problem seems to be on their behalf.

I'll let you know if it doesn't work in the future.

**Comment by okendoken** [comment]
@karolyi cool, thanks!
