### ISSUE TITLE
Labels without "for" attribute

### ISSUE THREAD

**Issue by strouhaljan** [flatlogic/awesome-bootstrap-checkbox#54]
Hi guys, I had difficulties using your library when building a web app. I had no unique ID for checkboxes and radios to pair them with labels. Only solution was to generate random ID and then use it.

I've found a solution to design checkboxes and radios in your way using your library with checkboxes (radios) nested inside of a label (no "for" and "id" attribute needed). I wish to present it to others. What's the best way to do it? Should I modify your files, or create new files or just fork your whole project and make a new one?

This could be my first contribution so I am sorry I don't know exactly, how it works :-)

**Comment by thatguyyoulove** [comment]
Generally the best way is to fork the project, make your alterations, commit them to your project, and then turn that commit into a pull-request for the original project (this one).

[Here's a helpful guide](https://help.github.com/articles/using-pull-requests/) for submitting GitHub pull-requests. 

If you need more help, feel free to reply here.

**Comment by DimaSavchenko** [comment]
Guys, thanks for your comments.
@thatguyyoulove offered the best way.
