### ISSUE TITLE
radio-single does not exist

### ISSUE THREAD

**Issue by ir-fuel** [flatlogic/awesome-bootstrap-checkbox#56]
In the documentation there is a reference to `radio-single`, however this is nowhere to be found in the css file.

**Comment by micrum** [comment]
Seems like this is reference to legacy code https://github.com/flatlogic/awesome-bootstrap-checkbox/commit/eb267b55f4b5a844a6c27c4fc105b6157e19c6cd

Thank you @ir-fuel, we will update documentation
