### ISSUE TITLE
Version 0.3.7 not on npm

### ISSUE THREAD

**Issue by LucasThielmann** [flatlogic/awesome-bootstrap-checkbox#58]
Hi,

the version currently deployed on npm ( https://www.npmjs.com/package/awesome-bootstrap-checkbox) is 0.3.6.

Unfortunately this version produces build errors concerning @fa-var-check that are fixed in 0.3.7.

Is there any reason 0.3.7 is not puplished on npm?

Regards,

Lucas

**Comment by vdh** [comment]
I was the one who bumped the version number to 0.3.7 due to the change I made in #55, so I'm guessing @okendoken doesn't yet know that the npm & bower packages needs to be redeployed?

**Comment by vdh** [comment]
The v0.3.7 tag is also missing here on the GitHub repo.

**Comment by DimaSavchenko** [comment]
Thanks! We released 0.3.6 and 0.3.7 on github and npm.
