### ISSUE TITLE
CSS class name conflict

### ISSUE THREAD

**Issue by kikonen** [flatlogic/awesome-bootstrap-checkbox#61]
I ran into problem since this library is binding itself directly into "checkbox" class of bootstrap. I had existing code, which is using checkbox (part of that inside library which I cannot change), and applying a-b-c into use broken all checkboxes in this context. 

My workaround (and proposed fix) is to add "aw-" prefix into all styles and a-b-c and and have it used something like this "checkbox aw-checkbox aw-checkbox-primary".

**Comment by geekdevs** [comment]
I agree, I have the same problem. Binding on css class with such widely used name as "checkbox" is overly ambitious, this definitely needs a prefix.

**Comment by DimaSavchenko** [comment]
Guys, thanks, accepted

**Comment by DimaSavchenko** [comment]
We change class name from .checkbox to .abc-checkbox in 1.0.0-alpha.1 version. 

Thanks!
