### ISSUE TITLE
In IE it is not pixel perfect.

### ISSUE THREAD

**Issue by AndorLundgren** [flatlogic/awesome-bootstrap-checkbox#62]
Have not found any way to fix the css myself. IE-checkboxes ticks are slightly lower.
![image](https://cloud.githubusercontent.com/assets/13776860/11264870/ca3923b2-8e97-11e5-894b-083f021820a9.png)

**Comment by DimaSavchenko** [comment]
Hi, @AndorLundgren! Sorry, but we don't have solution for this issue.
