### ISSUE TITLE
Re-Validating Awesome bootstrap Checkbox using FormValidatio.IO

### ISSUE THREAD

**Issue by rajukt** [flatlogic/awesome-bootstrap-checkbox#67]
How to revalidate Awesome Bootstrap Checkbox using Formvalidation.IO ..Revalidate is not Working ...
How to fire revalidate event in Formvalidatio.IO for Awesome Bootstrap Checkbox.
Can Anyone Help me??

**Comment by DimaSavchenko** [comment]
Hi, @rajukt! Sorry, but we don't have free time for resolving your issue.
