### ISSUE TITLE
Does not work with React

### ISSUE THREAD

**Issue by ir-fuel** [flatlogic/awesome-bootstrap-checkbox#68]
I wrote a react component that looks like this:

```
      <span>
        <div className="checkbox">
          <input
            className="checkbox"
            type="checkbox"
            id={this.props.id}
            defaultChecked={this.props.checked}
            onChange={this.toggle}
          />
          <label
            forHtml={this.props.id}
          >
          {this.props.name}
          </label>
        </div>
      </span>
```

`onChange` is never called.

When removing the `checkbox` class all works as expected.

**Comment by ir-fuel** [comment]
Seems I was using an outdated version of the css file. With the latest it works. The only issue is that the cursor does not show as a pointer.

**Comment by ir-fuel** [comment]
I seem to get this working by making the following modification to the CSS. No idea if this is the right way to go though:

```
.checkbox input[type="checkbox"],
.checkbox input[type="radio"] {
  opacity: 0;
  z-index: 1;
  transform: scale(1.5);
  cursor: pointer;
}
```

I added a 1.5 scale to the checkbox component and added a cursor type.

**Comment by DimaSavchenko** [comment]
Hi @ir-fuel ! Finally, What problems aren't solved ?
Thanks!

**Comment by ir-fuel** [comment]
The code I wrote simply doesn't allow me to click the checkbox, unless I start tampering with the CSS. The full explanation is in my first couple of posts here.
