### ISSUE TITLE
Screen Reader Issue with Label

### ISSUE THREAD

**Issue by evilduckz** [flatlogic/awesome-bootstrap-checkbox#70]
When using NVDA screen reader there is an issue reading the screen after an event. When using a checkbox in <div class="checkbox checkbox-primary checkbox-single"> the label is still required. Thus when the screen reader reads the check box (only AFTER an event) it will continue and read off "blank" after the checkbox.
e.g. see http://awesome-bootstrap-checkbox.okendoken.com/demo/index.html when the screen reader first reads either checkbox under heading "Checkboxes without label text .checkbox-single" it reads properly. However upon an check/uncheck event it will then read off "blank" after the next item.
steps to replicate:
1.first line read: "check box not checked single check box 1"
2.next line read is "check box checked single check box 2"
3.read previous line: "check box not checked single check box 1"
4.hit enter(to check the box) line reads: "checked"
5. next line then reads: blank
6. next line read: "check box checked single check box 2"
Thoughts?

**Comment by DimaSavchenko** [comment]
Hi, @evilduckz! Do you have solved your problem?
