### ISSUE TITLE
blue boxes around checkboxes/radios in Chrome

### ISSUE THREAD

**Issue by keverw** [flatlogic/awesome-bootstrap-checkbox#77]
Hi, 

I noticed in Chrome on Mac I'm getting blue boxes around checkboxes/radios in Chrome but not in firefox. I was trying `*:focus, *:active{ outline: none !important;}` with no success. Using the Bootstrap 3 version.

**Comment by nassa** [comment]
Adding the following override works for me:

    .checkbox input[type=checkbox]:focus + label::before,
    .checkbox input[type=radio]:focus + label::before {
        outline: none;
    }

**Comment by FranciscoG** [comment]
just want to note that removing :focus outlines hurts accessibility.  If you absolutely need to remove it then use some other form of indicating focus on element.   More info here:  [http://www.outlinenone.com/](http://www.outlinenone.com/)

Of course, that's if you care about the accessibility of your site, which many many people argue that you should

**Comment by keverw** [comment]
@FranciscoG Interesting. I noticed the regular browser checkboxes seem to only outline when tabbing, not clicking on them like these do. I wonder if it's possible to have styled checkboxes that emulate the native ones. Outlines make sense for tabbing, as people with screen readers may not be using a mouse. But when clicking or unclicking with the mouse they seem unneeded.

**Comment by FranciscoG** [comment]
@keverw  I see what you mean.  This is unavoidable with the way this css lib works.  It's using CSS to add focus styles to the label:before and when you add focus styles this way it considers a click a type of focus as well and that focus doesn't go away until you click on something else.  (I'd 100% confirm that, but I have experienced it multiple times so i'm almost sure this is a correct statement)

Unfortunately the only way to deal with this is either remove that [whole focus styling block](https://github.com/flatlogic/awesome-bootstrap-checkbox/blob/master/awesome-bootstrap-checkbox.css#L43) which would be bad for accessibility,  or use Javascript to detect mouse clicking and add another css class that removes that outlining.  I've had to do the JS way before in other projects.

here's an example of what I mean.  I'm just writing this off the cuff, you'd need to test it.  But you can see the general idea:

Add a css class that overrides the current one in this library
```css
.no-outline .checkbox input[type="checkbox"]:focus + label::before,
.no-outline .checkbox input[type="radio"]:focus + label::before,
.no-outline .radio input[type="radio"]:focus + label::before {
  outline: none; 
}
```

Use JS to detect a mouse click anywhere.  We're going to do it on the very mouse click detected on the document and add that css class to the body
```javascript
// using jQuery for the sake of an easy example
var userHasMouse = false;
$(document).on('click', function(e){
  if (!userHasMouse) {
    // do something here to remove outlines on focused elements
   $('body').addClass('no-outline');
  }
  userHasMouse = true;
});

```

**Comment by keverw** [comment]
@FranciscoG using Javascript sounds like a good workaround. One downside I can think is, it disables it for all checkboxes once a mouse click is made... What if someone else clicks the mouse helping them, then it would disable it even for the screen reader it sounds? Or even a better example, someone clicks and then later they tab when trying to be fast at a form.

Would it be possible to disable it only on the ones they clicked? Then when it loses focus, remove that class for next time? I was playing around this this idea but wasn’t having success. basically I gave a ID for the label too but the blur event didn’t seem to fire when you lost focus.

**Comment by AlissonRS** [comment]
For radio, this is what worked for me:

```
.radio input[type=radio]:focus + label::before {
    outline: none;
}
```

as the html looks like this:

```
<div class="radio">
  <input type="radio" name="something" />
  <label>Text</label>
</div>
```

However @FranciscoG solution should be considered due to acessibility.

**Comment by Soullighter** [comment]
I found where that outline is calling in bootstrap. It appers to be a box-shadow.
<img width="476" alt="Screen Shot 2019-12-10 at 9 23 22 AM" src="https://user-images.githubusercontent.com/10616549/70509018-1fd9c600-1b2f-11ea-8919-c7f1038bee74.png">

**Comment by vchapple17** [comment]
Using `outline:none` and `box-shadow: none` no longer worked for me to hide the focus styling.

I added the following to align the input's position to be behind the <label>'s version of the checkbox, but the visibility: hidden was crucial to hide the accessibility outlines. 

Note, the position change might be just due to my own css needs, but thought I'd include it for others just in case:

```
.abc-checkbox input[type="checkbox"] {
	position: absolute;
	visibility: hidden;
}
```
