### ISSUE TITLE
Why can't I use it without label?

### ISSUE THREAD

**Issue by xiasun** [flatlogic/awesome-bootstrap-checkbox#81]
This seems strange but every time i remove my label, the style disappear...

**Comment by matthax** [comment]
Hijacking:
If you use the following:
`<div class="checkbox checkbox-primary">
    <label>Enable
        <input class="styled" name="toggle" type="checkbox">
    </label>
  </div>`
The "checked" styling will not display properly. This isn't a huge issue but it becomes troublesome when creating the check-boxes dynamically or through templating since an ID is not always available.

**Comment by twifty** [comment]
This is an issue also effecting myself. I have a label with screen reader only content, which of course should not be rendered to the page. It seems the wrapper and label css selectors are tightly coupled.

**Comment by lokesh-coder** [comment]
The checkbox styles are directly bonded to label attribute. [https://github.com/flatlogic/awesome-bootstrap-checkbox/blob/master/awesome-bootstrap-checkbox.scss#L41](url)

`:before` psuedo class adds the white box, and `:after` adds the tick or check icon on top of the white box.  so, if label attribute is removed, the styles would not appear.

**Comment by kshipp** [comment]
+1.    
Need to find another way - using the Label is full of problems.  If it includes a label for another object, it's making ALL the labels near the checkbox to be active for this checkbox causing massive problems.

**Comment by CaptainHypertext** [comment]
+1 for what it's worth.  I don't like being forced to use an adjacent label, sometimes it doesn't work with the page layout.

**Comment by StudioJunkyard** [comment]
Using Label's with Input's is semantically correct for markup.

But I don't see why you couldn't modify the css to use elements other than `<label>`.
