### ISSUE TITLE
Undefined variable: "$input-border"

### ISSUE THREAD

**Issue by A50** [flatlogic/awesome-bootstrap-checkbox#87]
Line 55 of bower_components/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.scss: Undefined variable: "$input-border"

**Comment by craigbartholomew** [comment]
+1

**Comment by craigbartholomew** [comment]
Import Bootstrap (the variables at least) before awesome-bootstrap-checkbox.scss.

**Comment by Angelixion** [comment]
I have the same error, how i import the variables/bootstrap in gulp?

**Comment by ahonymous** [comment]
Hi. I am include the variables as '@import "../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/_variables.scss"'.
It worked.

**Comment by kikonen** [comment]
In 1.0.0-alpha.4 I'm hitting issue due to missing $input-border-color variable.

workaround:
$input-border-color: $input-border;

**Comment by PanzerKunst** [comment]
node_modules\awesome-bootstrap-checkbox\awesome-bootstrap-checkbox.scss
    Error: Undefined variable: "$input-border-color".
        on line 53 of node_modules/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.scss

**Comment by shoudaos** [comment]
for 1.0.0-alpha.4 it is because you need to use bootstrap 4, not 3. version below 1.0.0-alpha is using bs3
