### ISSUE TITLE
All radio buttons are in in indeterminate state

### ISSUE THREAD

**Issue by sidzan** [flatlogic/awesome-bootstrap-checkbox#92]
I am using Radio Buttons as checkboxes as guided in the walk through [http://flatlogic.github.io/awesome-bootstrap-checkbox/demo/](link)

However the problem for me is all the checkboxes are in indeterminate state which i do not want to use  and is a bit annoying to see every time. Possibly i am not using it the correct way but i could not find any workaround solution for the issue.

The following is my code .

`<div className="col-sm-9">`
`{function() {`
`if (this.state.order_data.contact_id.plr_require_price_plan && !grocery) return;`
`return <div className="checkbox checkbox-success">`
`<input type="radio" name="plan" value="order" onClick={this.onchange_price_plan} checked={this.state.pay_for=="order"} id ="order"/><label htmlFor="order">{utils.format_money(this.state.order_data.plr_due_amount)}  THB: just this order</label>`
`</div>`
`}.bind(this)()}`
`{function() {`
`if (this.state.order_data.plr_due_amount>7500) return;`
`return <div className="checkbox checkbox-success">`
`<input type="radio" name="plan" value="plan1" onClick={this.onchange_price_plan} checked={this.state.pay_for=="plan1"} id="plan1"/><label htmlFor="plan1">7,500 THB: Paleo Savage Package</label>`
`</div>`
`}.bind(this)()}`
`{function() {`
`if (this.state.order_data.plr_due_amount>17500) return;`
`return <div className="checkbox checkbox-success">`
`<input type="radio" name="plan" value="plan2" onClick={this.onchange_price_plan} checked={this.state.pay_for=="plan2"} id="plan2"/><label htmlFor="plan2">17,500 THB: Paleo Warrior Package</label>`
`</div>`
`}.bind(this)()}`
`{function() {`
`if (this.state.order_data.plr_due_amount>47500) return;`
`return <div className="checkbox checkbox-success">`
`<input type="radio" name="plan" value="plan3" onClick={this.onchange_price_plan} checked={this.state.pay_for=="plan3"} id="plan3"/><label htmlFor="plan3">47,500 THB: Paleo Chieftain Package</label>`
`</div>`
`}.bind(this)()}`
`</div>`

Any help or suggestion will be appreciated. :+1:

**Comment by mehdi1802** [comment]
I have same problem. If there is no "checked" attribute then all radio buttons show in indeterminate state

**Comment by Luc45** [comment]
Also having this issue. The radios should start blank.

**Comment by MaxenceMouchard** [comment]
Same bug, this ticket has been closed without conclusion ?
