### ISSUE TITLE
Small gap between checkox/radio and label

### ISSUE THREAD

**Issue by kikonen** [flatlogic/awesome-bootstrap-checkbox#93]
There is small noticeable gap between checkbox/radio and label. This area is unresponsive and doesn't react into mouse clicks. Issue is noticeable in demo page also (look into mouse pointer when hovering over widgets).

Problem: This causes that checkboxes appear sometimes unresponsive, when user is trying to target checkbox icon, but instead mouse click hits this unresponsive gap area.

**Comment by DhruvPrakash** [comment]
Hi, I worked around this issue by giving the checkbox an id attribute and the label a for attribute referencing the checkbox's id.

**Comment by kikonen** [comment]
Since accessibility requirements alteady require binding label and checkbox together thst doesn't change situation. I.e small gap between them.
