### ISSUE TITLE
Select all checkbox only works one-time

### ISSUE THREAD

**Issue by jbweb** [flatlogic/awesome-bootstrap-checkbox#94]
When creating a "select-all" checkbox with some simple jQuery, "_awesome-bootstrap-checkbox_" only works one time!
On the first click i give all checkboxes the checked attribute, and on the second click i remove all checked attributes (also tried setting checked attribute to false, but same result).

The first way around works perfectly, but when repeating the process (thus selecting all for the second time), nothing happens to the awesome-bootstrap-checkbox replacements. When checking the DOM, the input fields themself are working.

Here is my example:
[https://jsfiddle.net/abkvzt7v/](https://jsfiddle.net/abkvzt7v/)

**Comment by nikrabaev** [comment]
@jbweb you probably should use 'prop' method instead of 'attr'.
Working fiddle: https://jsfiddle.net/4yqyowpj/

**Comment by DimaSavchenko** [comment]
@nikrabaev, Thanks!
