### ISSUE TITLE
Missing .LESS file

### ISSUE THREAD

**Issue by christopherjohns1** [flatlogic/awesome-bootstrap-checkbox#96]
After installing the package using npm, and attempting to compile LESS, I received an error:

`FileError: '../../node_modules/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.less' wasn't found. Tried - src\node_modules\awesome-bootstrap-checkbox\awesome-bootstrap-checkbox.less,node_modules\awesome-bootstrap-checkbox\awesome-bootstrap-checkbox.less,..\..\node_modules\awesome-bootstrap-checkbox\awesome-bootstrap-checkbox.less in src\less\bootstrap-link-theme\_bootstrap-import.less`

After a fresh install of awesome-bootstrap-checkbox using npm, the file structure is:

> demo
> awesome-bootstrap-checkbox.css
> awesome-bootstrap-checkbox.scss
> bower.json
> LICENSE
> package.json
> README.md

I am able to download the awesome-bootstrap-checkbox.less file, insert it into place, and it works successfully, but it appears that npm is not creating the file successfully.

**Comment by DimaSavchenko** [comment]
Hi! We don't support LESS in new version(v 1.0.0), because bootstrap v4 also don't support LESS.
For support LESS use awesome-bootstrap-checkbox v0.3.7.
Thanks!
