### ISSUE TITLE
MVC Projects - Checkbox not checkable

### ISSUE THREAD

**Issue by wintran** [flatlogic/awesome-bootstrap-checkbox#97]
I have found an issue with this CSS style and MVC rendered checkboxes using MVC helpers.

For example, code like this in a Razor view:

```
<div class="checkbox">
    @Html.CheckBoxFor(model => model.Field1)
    <label for="Field1">Field Name</label>
</div>
```

Will render this:

```
<div class="checkbox">
  <input id="Field1" name="Field1" type="checkbox" value="true">
  <input name="Field1" type="hidden" value="false">
  <label for="Field1">Field Name</label>
</div>
```

Notice that a hidden input box will be inserted into the html code to return unchecked values.  This will not be handled by your CSS styles because it strictly wants a input tag followed by label tag.

I fixed the issue by add an additional style to handle hidden field.  So for example:

`.checkbox input[type="checkbox"]:focus + label::before,
`

I also added the following line to detect for hidden field:
`.checkbox input[type="checkbox"]:focus + input[type="hidden"] + label::before,
`

I attached the new JS file I used to fix the style for MVC rendered checkboxes.
[bootstrap-checkbox.txt](https://github.com/flatlogic/awesome-bootstrap-checkbox/files/391741/bootstrap-checkbox.txt)

**Comment by bjarnef** [comment]
I have the same issue.. in MVC `Html.CheckBoxFor` add a hidden input to ensure a value is submitted for unchecked checkboxes. It seems it works if the hidden input is added before checkbox in DOM, but ASP.NET MVC add it after by default.. I am not sure if there is a way to add the hidden field before checkbox without using javascript.

**Comment by AlissonRS** [comment]
This is not the first style for checkboxes I used and it didn't work well with the extra hidden input added by MVC. @wintran your solution worked well, I think this should be commited into the master branch. Thanks for sharing your fix, I've lost almost an hour trying to figure out this. Such a pain.

**Comment by GorillaSpring** [comment]
Thanks.  The solution from @wintran worked, but I would like to use the LESS file.

Can't seem to edit the LESS file to make this work.  CSS is not a strong suit for me.  LESS even "less" so (pun intended!)

If this is closed with a fix or is someone wants to post a corrected less file, that would be appreciated.

FYI to others.  If you want to add the "styled" class, this is how I am doing this,   Also if you need validation (for some reason), you need to put it after the label.
`
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox checkbox-primary">
                    @Html.CheckBoxFor(model => model.Check1, new { @class = "styled" })
                    <label for="Check1">
                        Label for Check 1
                    </label>
                    @Html.ValidationMessageFor(model => model.Check1, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
`

**Comment by jscontrust** [comment]
Hi, I created a fork which does the changes for SCSS:
https://github.com/jscontrust/awesome-bootstrap-checkbox

**Comment by jppalma** [comment]
Quick question if someone can help me with. 

Is there an easy way of moving the label to the left side of the checkbox? 

I'm using Wintran css

Tks
